version: '3.7'

services:

  mongo:
    image: mongo

    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

    networks:
      - bike-mapper

    ports:
      - ${MONGO_PORT}:${MONGO_PORT}

    volumes:
      - ./bike_mapper_db_mongo:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express

    restart: unless-stopped

    ports:
      - ${ME_CONFIG_PORT}:${ME_CONFIG_PORT}

    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}
      # ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}

    depends_on:
      - mongo

    networks:
      - bike-mapper

  api:
    build:
      context: .
      dockerfile: ./Dockerfile

    image: bike-mapper-api

    links:
      - "mongo"

    container_name: bike-mapper-api

    volumes:
      - .:/app
      - ./node_modules:/app/node_modules

    ports:
      - ${API_PORT}:${API_PORT}

    environment:
      API_PORT: ${API_PORT}
      # REACT_APP_API_DOMAIN: ${REACT_APP_API_DOMAIN}
      MONGO_PORT: ${MONGO_PORT}

    command:  ./entrypoint.sh

    networks:
      - bike-mapper

    depends_on:
      - mongo

volumes:
  bike_mapper_db_mongo:

networks:
  bike-mapper:
    driver: bridge
