version: "3.7"

services:

  mongo:

    build:
      dockerfile: ./dockerfiles/Dockerfile-mongo
      context: .

    image: bike-mapper/mongo

    container_name: bike-mapper-mongo

    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

    networks:
      - bike-mapper

    ports:
      - ${MONGO_PORT}:${MONGO_PORT}

    volumes:
      - bike_mapper_db_mongo:/data/db

  mongo-express:

    build:

      dockerfile: ./dockerfiles/Dockerfile-mongo-express
      context: .

    image: bike-mapper/mongo-express

    container_name: bike-mapper-mongo-express

    restart: unless-stopped

    ports:
      - ${ME_CONFIG_PORT}:${ME_CONFIG_PORT}

    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}

    depends_on:
      - mongo

    networks:
      - bike-mapper

  api:

    build:
      dockerfile: ./dockerfiles/Dockerfile-api
      context: .

    image: bike-mapper/api

    links:
      - mongo

    container_name: bike-mapper-api

    volumes:
      - ./entrypoints/entrypoint-api.sh:/usr/local/bin/entrypoint.sh

    working_dir: /bike-mapper

    command: entrypoint.sh

    ports:
      - ${API_PORT}:${API_PORT}

    environment:
      API_PORT: ${API_PORT}
      MONGO_PORT: ${MONGO_PORT}

    networks:
      - bike-mapper

  app:

    build:
      dockerfile: ./dockerfiles/Dockerfile-app
      context: .

    image: bike-mapper/app

    container_name: bike-mapper-app

    volumes:
      - ./entrypoints/entrypoint-app.sh:/usr/local/bin/entrypoint.sh

    working_dir: /bike-mapper

    command: entrypoint.sh

    environment:
        PORT: ${APP_PORT}
        APP_API_DOMAIN: ${APP_API_DOMAIN}
        APP_API_PORT: ${API_PORT}

    ports:
      - ${APP_PORT}:${APP_PORT}

    networks:
      - bike-mapper

volumes:
  bike_mapper_db_mongo:

networks:
  bike-mapper:
    driver: bridge